### ISSUE TITLE
Time Zone complains about wrong disk

### ISSUE THREAD

**Issue by einstein95** [a2-4am/passport#107]
Used MAME's apple2ee driver with Passport 2021-09-14 and the WOZ images from https://archive.org/download/ApplesauceImages/Time%20Zone%20%28Sierra%20On-Line%29/

When booting from "Disk A" WOZ, I get the titlescreen but when using the cracked DSK the game complains about not being the right disk

Passport log:
![0000](https://user-images.githubusercontent.com/2461173/148750101-bb8246f2-6bb7-4c48-bfa1-6f5d43f5e88c.png)

Error screen:
![0001](https://user-images.githubusercontent.com/2461173/148750120-a5130183-36fd-44e1-9300-40603d5cac8f.png)

Resulting cracked DSK:
[timezoned1a.zip](https://github.com/a2-4am/passport/files/7838123/timezoned1a.zip)

**Comment by xotmatrix** [comment]
Time Zone needs some special handing because it uses DOS volume numbers to identify disks. DSK disk images do not support volume numbers so the game needs extensive patching.

Enjoy this full explanation:
https://ia800108.us.archive.org/8/items/TimeZone4amCrack/Time%20Zone%20%284am%20and%20san%20inc%20crack%29.txt
